theme: jekyll-theme-tactile
title: Erick Martinez
description: MA Mathematics (Probability) & Dipl. Financial Engineering Graduate Student | Stochastic Modeling, Optimization & Green Finance | BSc. Applied Mathematics & Physics
